services:
    app_graph_ql.resolver.doctrine:
        class: AppGraphQLBundle\Resolver\DoctrineResolver
        arguments:
          - "@doctrine.orm.entity_manager"
        abstract: true

    app_graph_ql.resolver.post:
        class: AppGraphQLBundle\Resolver\PostResolver
        parent: app_graph_ql.resolver.doctrine

    app_graph_ql.resolver.user:
        class: AppGraphQLBundle\Resolver\UserResolver
        parent: app_graph_ql.resolver.doctrine