AppBundle\Entity\Comment:
  attributes:
      id:
        groups: ['comment_read', 'post_read']
      content:
        groups: ['comment_read', 'comment_create', 'post_read']
      authorEmail:
        groups: ['comment_read', 'post_read']
      publishedAt:
        groups: ['comment_read', 'post_read']
      post:
        groups: ['comment_create']
